language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
  - "2.3"
  - "4.0"
  - "5.0"
before_install:
  - npm install -g grunt-cli
  - npm install coffee-script
before_script: grunt build
script: npm run-script test-cov
after_success:
  - test -e ./coverage/lcov.info && npm install codeclimate-test-reporter && codeclimate-test-reporter
    < ./coverage/lcov.info
notifications:
  email:
    - snowyu.lee@gmail.com
addons:
  code_climate:
    repo_token:
      secure: "bnRZVmO7xIU3z7qt9lJWSWJE9xV2zOjRkUPEnGq9u5Myg8SSOEvxhTFAoqJiYFEXGdZEv0IkPISANiARmeNEHaMZsrBVvl6WgaOGq5KiQV3lAALwzVXsjYITxqFkenlMwFX98mFx//b/MGWsePACBNGaB70V9izrfLYYO8lYrEdVA5nIkaH2esWdNU2Ocnw+2vj6QNJmTT3QQbzfUPTiFqM2P5yELTTDQeTZ+hIAi4vxIF5wdlwR2nTvRQ3csgE/M4zvMM+IZOUpLABLvf7dh6QeCwN68iUxv6SEDK5ppUDI0MJNj4SNpPlJbAEqMzrvz5V7EnM5THzrmgk0yNZ6Gqi7Kz2KDxfhGvl7iP7x/Ff8nuM1snMq3wBVLGq0Sh7TjdekhEDAr4BwBkVd4ZUWBQjoCgV1mC7Xb4pyDqC4laLwWxOMKpGB+jG+60viwScdQbc6/FxImXOuFgkllry7zhusO2AaDpgKZsl89I8YxzFL5VElolMl02LY5lxODuYVOe1MHDgA/g1myhCvrMdLG/FWeLi+WgmZrHOQVuiX12/A4lnoYjRwOX5gSNEIc3tH5JyTm3vV7aJUFWlVmZ5FulBT2QND0z5axthZikb845HMxGwpFmhFn/Ahdodl/aRYO2aaqHkIESFg4EbtX0+F+2xrY1H0pY73dBICWPJIewQ="
